// Code generated by MockGen. DO NOT EDIT.
// Source: internal/builder/template_cache.go
//
// Generated by this command:
//
//	mockgen -source=internal/builder/template_cache.go -destination=internal/builder/mock_template_cache_test.go -package=builder_test
//

// Package builder_test is a generated GoMock package.
package builder_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheManager is a mock of CacheManager interface.
type MockCacheManager struct {
	ctrl     *gomock.Controller
	recorder *MockCacheManagerMockRecorder
	isgomock struct{}
}

// MockCacheManagerMockRecorder is the mock recorder for MockCacheManager.
type MockCacheManagerMockRecorder struct {
	mock *MockCacheManager
}

// NewMockCacheManager creates a new mock instance.
func NewMockCacheManager(ctrl *gomock.Controller) *MockCacheManager {
	mock := &MockCacheManager{ctrl: ctrl}
	mock.recorder = &MockCacheManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheManager) EXPECT() *MockCacheManagerMockRecorder {
	return m.recorder
}

// ClearCache mocks base method.
func (m *MockCacheManager) ClearCache(templateOnly bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCache", templateOnly)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCache indicates an expected call of ClearCache.
func (mr *MockCacheManagerMockRecorder) ClearCache(templateOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCache", reflect.TypeOf((*MockCacheManager)(nil).ClearCache), templateOnly)
}

// GetCacheDir mocks base method.
func (m *MockCacheManager) GetCacheDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheDir indicates an expected call of GetCacheDir.
func (mr *MockCacheManagerMockRecorder) GetCacheDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheDir", reflect.TypeOf((*MockCacheManager)(nil).GetCacheDir))
}

// GetTemplateCachePath mocks base method.
func (m *MockCacheManager) GetTemplateCachePath(version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateCachePath", version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateCachePath indicates an expected call of GetTemplateCachePath.
func (mr *MockCacheManagerMockRecorder) GetTemplateCachePath(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateCachePath", reflect.TypeOf((*MockCacheManager)(nil).GetTemplateCachePath), version)
}
