// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pipeline/gradle_build.go
//
// Generated by this command:
//
//	mockgen -source=internal/pipeline/gradle_build.go -destination=internal/pipeline/mock_gradle_build_test.go -package=pipeline
//

// Package pipeline is a generated GoMock package.
package pipeline

import (
	reflect "reflect"

	builder "github.com/na2na-p/mnemonic/internal/builder"
	gomock "go.uber.org/mock/gomock"
)

// MockgradleBuilder is a mock of gradleBuilder interface.
type MockgradleBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockgradleBuilderMockRecorder
	isgomock struct{}
}

// MockgradleBuilderMockRecorder is the mock recorder for MockgradleBuilder.
type MockgradleBuilderMockRecorder struct {
	mock *MockgradleBuilder
}

// NewMockgradleBuilder creates a new mock instance.
func NewMockgradleBuilder(ctrl *gomock.Controller) *MockgradleBuilder {
	mock := &MockgradleBuilder{ctrl: ctrl}
	mock.recorder = &MockgradleBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgradleBuilder) EXPECT() *MockgradleBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockgradleBuilder) Build(buildType string) (builder.BuildResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", buildType)
	ret0, _ := ret[0].(builder.BuildResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockgradleBuilderMockRecorder) Build(buildType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockgradleBuilder)(nil).Build), buildType)
}
